### PR TITLE
Implemented two-way and server-to-specific-client communication

### PR DESCRIPTION
**Pull request by chris-ray**
Created HubActor and ClientActor base actors to totally abstract away
the connectivity details. Servers can now send messages to specific
clients, and clients can now talk back to the server.

### CODE REVIEW

**Comment by chris-ray** [comment]
May need to update the gifs on readme

**Comment by marcpiechura** [comment]
:+1: 

Some notes
- If somebody would use become in a subclass of ClientActor and HubActor all defined receive handler will be lost and if somebody defines another Receive in the constructor it will throw an exception because it is defined after ReceiveAny, afaik.
- The current workflow with the ClientID was a simple hack from me and therefore isn't working reliably, so I will change this implementation to something that really works ;)

**Comment by chris-ray** [comment]
Agreed. Now I'm thinking an abstract hubactor is just noise. A "hub" is really just a proxy to the sender you hand in with the hub started message. When I get some time I think I will rename hub to hubproxy, remove the abstract hubactor concept, and just make it more straightforward on how to interact without introducing unneeded complexity. So what's not working with clientid?

**Comment by marcpiechura** [comment]
Sounds good.

For example let's assume a client connects to the hub but the joined message isn't transferred to the client because of some network issue or so and in the next second another client joined the hub, then the first client will also use this clientId as his own since it's the first joined message he received. 
You can see the fix here https://github.com/Silv3rcircl3/Akka.Signal/commit/ec12732d8663b9e4da3e34714072816d64e672e0 what's missing is that the client sends join messages every x second until he receives a joined message with self = true. 

I think we should rethink the complete design once we have time and test and document everything.

**Pull request merged**
